version: '3'

services:

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
    volumes:
      - mysql-files:/var/lib/mysql

  wordpress-dev:
    image: wordpress-dev:${WORDPRESS_VERSION}-wc${WOOCOMMERCE_VERSION}
    build:
      context: ./docker-images
      dockerfile: Dockerfile.wordpress
      args:
        - WORDPRESS_VERSION
        - WOOCOMMERCE_VERSION
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG',     true);
        define('WP_DEBUG_DISPLAY', true);
    volumes:
      - ./woocommerce-extra-checkout-fields-for-brazil:/var/www/html/wp-content/plugins/woocommerce-extra-checkout-fields-for-brazil
      - ./woocommerce-abbiamolog:/var/www/html/wp-content/plugins/woocommerce-abbiamolog
    ports:
      - 8080:80
    depends_on:
      - db

  composer:
    build:
      context: ./docker-images
      dockerfile: Dockerfile.composer
    volumes:
      - ./woocommerce-abbiamolog:/woocommerce-abbiamolog

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: wordpress
    depends_on:
      - db

volumes:
  mysql-files:
  wordpress-test-5.6-wc4.9.1:
  wordpress-test-5.6-wc4.8.0:
  wordpress-test-5.6-wc4.7.1:
  wordpress-test-5.6-wc4.6.2:
  wordpress-test-5.6-wc4.5.2:
  wordpress-test-5.6-wc4.4.1:
  wordpress-test-5.6-wc4.3.3:
  wordpress-test-5.6-wc4.2.2:
  wordpress-test-5.6-wc4.1.1:
  wordpress-test-5.6-wc4.0.0:
  wordpress-test-5.6-wc3.9.3:
